name: PR Number

on:
  pull_request:
  issue_comment:

jobs:
  GetPR-Win:
    runs-on: windows-2019
    steps:
      - name: Get PR Number
        id: get_pr
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "issue_comment") {
            Write-Host "::set-output name=pr_number::${{ github.event.issue.number }}"
          }
          else {
            Write-Host "::set-output name=pr_number::${{ github.event.pull_request.number }}"
          }
      - name: Get PR Details
        id: pr_details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/cocos/cocos-engine/pulls/${{ steps.get_pr.outputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse Pull Request
        id: parse_pr
        shell: pwsh
        run: |
          $pull_request = @"
          ${{ steps.pr_details.outputs.data }}
          "@ | ConvertFrom-Json
          Write-Host $pull_request
          Write-Host "::set-output name=pr_html_url::$($pull_request.html_url)"
          Write-Host "::set-output name=pr_author::$($pull_request.user.login)"
          Write-Host "::set-output name=pr_head_ref::$($pull_request.head.ref)"
          Write-Host "::set-output name=pr_head_sha::$($pull_request.head.sha)"
          Write-Host "::set-output name=pr_base_ref::$($pull_request.base.ref)"
          Write-Host "::set-output name=pr_base_sha::$($pull_request.base.sha)"
      - name: Check Job Parameter
        run: |
          echo "${{ steps.parse_pr.outputs.pr_head_ref }}"
          echo "${{ steps.parse_pr.outputs.pr_head_sha }}"
          echo "${{ steps.parse_pr.outputs.pr_base_ref }}"
          echo "${{ steps.parse_pr.outputs.pr_base_sha }}"
